- name: Demo playbook for Ansible Template Demo
  hosts: localhost
  gather_facts: false
  vars:
    title: User_Directory
    user_name: John
    user_location: India
    user_age: 21
    user_role: admin
    users:
      - someuser1
      - someuser2
      - someuser3
      - someuser4
      - someuser5
    users_detail:
      - name: User1
        location: country1
        age: 21
        role: admin
      - name: user2
        location: country2
        age: 31
        role: operator
      - name: user3
        location: country3
        age: 41
        role: developer
  tasks:
    - name: Debug tasks Jinja2
      ansible.builtin.debug:
        msg: | 
          {% macro greet(name) %}
          Hello, {{ name }}!
          {% endmacro %}

          {% for user in users_detail %}
          {{ greet(user.age) }}
          {% endfor %}

    - name: Create a file from template
      ansible.builtin.template:
        src: example.j2
        dest: example.md

    - name: Create a html file using template inheritance
      ansible.builtin.template:
        src: child.j2
        dest: sample.html